#include QMK_KEYBOARD_H

enum keycodes {
        CC_ARIN = SAFE_RANGE, // Å
        CC_ADIA,              // Ä
        CC_ODIA,              // Ö
        CC_ALPH,
        CC_BETA,
        CC_DELT,
        CC_GAMM,
        CC_SIGM,
        CC_RHO,
        CC_PI,
        CC_SNEK,
};

enum layer_names{
        _BASE = 0,
        _UCIS,
        _SYMBOLS,
        _NUMPAD,
        _NAV,
        _FUNCTION,
        _UNUSED_2,
        _UNUSED_3,
        _UNUSED_4,
        _UNUSED_5,
        _UNUSED_6,
        _UNUSED_7,
        _UNUSED_8,
        _UNUSED_9,
        _UNUSED_10,
        _UNUSED_11
};

/*
 * Home-row mods
 */
#define HOME_A LGUI_T(KC_A)
#define HOME_S LALT_T(KC_S)
#define HOME_F LCTL_T(KC_F)
#define HOME_J LCTL_T(KC_J)
#define HOME_L LALT_T(KC_L)
#define HOME_SCLN LGUI_T(KC_SCLN)
#define LSFT_ENT LSFT_T(KC_ENT)
#define LSFT_SPC LSFT_T(KC_SPC)

/*
 * Mod-taps
 */
#define CONTROL_SPC LT(_NAV, KC_SPC)

#ifdef OLED_ENABLE
        #include "oled.c"
#endif
/*
 * Tapd-dances
 */
#ifdef TAP_DANCE_ENABLE
        #include "tapdance.c"
        #define ESC_CAP TD(TD_ESC_CAPS)
        #define TD_LEFT TD(TD_LEFT_HOME) 
        #define TD_DOWN TD(TD_DOWN_PGDN) 
        #define TD_UP   TD(TD_UP_PGUP)
        #define TD_RGHT TD(TD_RGHT_END)
        #define TD_BSLS TD(TD_BSLS_GRV)
        #define TD_PIPE TD(TD_PIPE_TILD)
#else
        #define ESC_CAP KC_ESC
        #define TD_LEFT KC_LEFT
        #define TD_DOWN KC_DOWN
        #define TD_UP   KC_UP
        #define TD_RGHT KC_RGHT
        #define TD_BSLS KC_BSLS
        #define TD_PIPE KC_PIPE
#endif
/*
 * Combos
 */
#ifdef COMBO_ENABLE
        #include "combos.c"
#endif
/*
 * Unicode map
 */
#ifdef UNICODEMAP_ENABLE
        #include "unicode_map.c"
#endif
/*
 * Unicode UCIS
 */
#ifdef UCIS_ENABLE
        #include "ucis.c"
#endif
/*
 * Leader key
 */
#ifdef LEADER_ENABLE
        #include "leader.c"
#endif

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

        /*
         * Base layer, QWERTY layout with homerow-mods (except shift), mod tap for enter and space / shift, combos for tab and escape.
         * As well as Swedish characters.
         * Access to _NUMPAD and _SYMBOLS layers on the thumbs.
         */
	[_BASE] = LAYOUT(
/* ┌──────┬──────┬──────┬──────┬──────┐                  ┌──────┬──────┬──────┬──────┬──────┐
 * │  Q   │  W  TAB E   │  R   │  T   │                  │  Y   │  U  BSP I   Å  O   │  P   │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │ A/◆  │ S/⎇ ESC D   │ F/⎈  │  G   │                  │  H   │ J/⎈ ENT K   Ä L/⎇  │ ;/◆  │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │  Z   │  X   │  C   │  V   │  B   │                  │  N   │  M   │ , <  Ö . >  │ / ?  │
 * └───────────────────────────┼──────┼──────┐    ┌──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │Spc/⇧ │NUMPAD│    │SYMBOL│ ⏎/⇧  │
 *                             │      │      │    │      │      │
 *                             └──────┴──────┘    └──────┴──────┘
 *                                                                                   generated by [keymapviz] */
                        KC_Q   , KC_W   , KC_E   , KC_R   , KC_T,                                               KC_Y   , KC_U   , KC_I   , KC_O   , KC_P,
                        HOME_A , HOME_S , KC_D   , HOME_F , KC_G,                                               KC_H   , HOME_J , KC_K   , HOME_L , HOME_SCLN,
                        KC_Z   , KC_X   , KC_C   , KC_V   , KC_B,                                               KC_N   , KC_M   , KC_COMM, KC_DOT , KC_SLSH,
                                                            LSFT_SPC, MO(_NUMPAD),          MO(_SYMBOLS), LSFT_ENT
                       ),
        /*
         * _UCIS Is used for unicode input, the UCIS system requires basic keycodes A-Z, a-z, 0-9 ONLY, no mod-taps, homerow-mods, etc...
         */
	[_UCIS] = LAYOUT(
/* ┌──────┬──────┬──────┬──────┬──────┐                  ┌──────┬──────┬──────┬──────┬──────┐
 * │  Q   │  W   │  E   │  R   │  T   │                  │  Y   │  U   │  I   │  O   │  P   │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │  A   │  S   │  D   │  F   │  G   │                  │  H   │  J   │  K   │  L   │      │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │  Z   │  X   │  C   │  V   │  B   │                  │  N   │  M   │      │      │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┐    ┌──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │Space │NUMPAD│    │      │  ⏎   │
 *                             │      │      │    │      │      │
 *                             └──────┴──────┘    └──────┴──────┘
 *                                                                                   generated by [keymapviz] */
                        KC_Q   , KC_W   , KC_E   , KC_R   , KC_T   ,                           KC_Y   , KC_U   , KC_I   , KC_O   , KC_P,
                        KC_A   , KC_S   , KC_D   , KC_F   , KC_G   ,                           KC_H   , KC_J   , KC_K   , KC_L   , XXXXXXX,
                        KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   ,                           KC_N   , KC_M   , XXXXXXX, XXXXXXX, XXXXXXX,
                                                   KC_SPC , MO(_NUMPAD),              XXXXXXX, KC_ENT
                       ),
        /*
         * _SYMBOLS gives access to a number row as well as a bunch of symbols. Leader key on left thumb, as well as access to the _FUNCTION layer.
         */
	[_SYMBOLS] = LAYOUT(
/* ┌──────┬──────┬──────┬──────┬──────┐                  ┌──────┬──────┬──────┬──────┬──────┐
 * │  !   │  @   │  #   │  $   │  %   │                  │  ^   │  &   │  {   │  }   │  *   │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │  α   │  β   │  δ   │  π   │ \ `  │                  │ - _  │  =   │  (   │  )   │ ' "  │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │  γ   │  σ   │  ρ   │  🐍  │ | ~  │                  │  _   │  +   │  [   │  ]   │  ~   │
 * └──────┴──────┴──────┴──────┼──────┼──────┐    ┌──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │LEADER│ NAV  │    │      │      │
 *                             │      │      │    │      │      │
 *                             └──────┴──────┘    └──────┴──────┘
 *                                                                                   generated by [keymapviz] */
                        KC_EXLM, KC_AT  , KC_HASH, KC_DLR , KC_PERC,                             KC_CIRC, KC_AMPR, KC_LCBR, KC_RCBR, KC_ASTR,
                        CC_ALPH, CC_BETA, CC_DELT, CC_PI  , TD_BSLS,                             KC_MINS, KC_EQL , KC_LPRN, KC_RPRN, KC_QUOT,
                        CC_GAMM, CC_SIGM, CC_RHO , CC_SNEK, TD_PIPE,                             KC_UNDS, KC_PLUS, KC_LBRC, KC_RBRC, KC_TILD,
                                                            QK_LEAD, MO(_NAV),    XXXXXXX, XXXXXXX
                        ),
        /*
         * _NUMPAD gives acces to a numpad like layout on the right hand, RGB settings on the left and access to the _FUNCTION layer on the right thumb.
         */
	[_NUMPAD] = LAYOUT(
/* ┌──────┬──────┬──────┬──────┬──────┐                  ┌──────┬──────┬──────┬──────┬──────┐
 * │      │Sat ↑ │Hue ↑ │Val ↑ │RGB ↻ │                  │  *   │  7   │  8   │  9   │ - _  │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │RGB ⏼ │Sat ↓ │Hue ↓ │Val ↓ │RGB ↺ │                  │ / ?  │  4   │  5   │  6   │  +   │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │      │      │Tap ↑ │Tap ↓ │PrtTap│                  │      │  1   │  2   │  3   │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┐    ┌──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │ NAV  │    │      │  0   │
 *                             │      │      │    │      │      │
 *                             └──────┴──────┘    └──────┴──────┘
 *                                                                                   generated by [keymapviz] */
                        XXXXXXX, RGB_SAI, RGB_HUI, RGB_VAI, RGB_MOD,                                 KC_ASTR, KC_7   , KC_8   , KC_9   , KC_MINS,
                        RGB_TOG, RGB_SAD, RGB_HUD, RGB_VAD, RGB_RMOD,                                KC_SLSH, KC_4   , KC_5   , KC_6   , KC_PLUS,
                        XXXXXXX, XXXXXXX, DT_UP  , DT_DOWN, DT_PRNT,                                 XXXXXXX, KC_1   , KC_2   , KC_3   , XXXXXXX,
                                                            XXXXXXX, XXXXXXX,              MO(_NAV), KC_0
                        ),
        /*
         * Access backspace and quotation symbols. As well as arrow navigation (vim layout) and home, page up, page down, and end keys with double taps.
         * Left thumb triggers Caps Word.
         */
	[_NAV] = LAYOUT(
/* ┌──────┬──────┬──────┬──────┬──────┐                  ┌──────┬──────┬──────┬──────┬──────┐
 * │  🔊  │  F7  │  F8  │  F9  │ F10  │                  │CapWrd│ COPY │PASTE │      │      │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │  🔉  │  F4  │  F5  │  F6  │ F11  │                  │ ← ⇐  │ ↓ ⇓  │ ↑ ⇑  │ → ⇒  │ ' "  │
 * ├──────┼──────┼──────┼──────┼──────┤                  ├──────┼──────┼──────┼──────┼──────┤
 * │  🔇  │  F1  │  F2  │  F3  │ F12  │                  │ ⏮   │ ⏯   │ ⏭   │      │      │
 * └──────┴──────┴──────┴──────┼──────┼──────┐    ┌──────┼──────┼──────┴──────┴──────┴──────┘
 *                             │      │      │    │      │      │
 *                             │      │      │    │      │      │
 *                             └──────┴──────┘    └──────┴──────┘
 *                                                                                   generated by [keymapviz] */
                        KC_KB_VOLUME_UP  , KC_F7  , KC_F8  , KC_F9  , KC_F10 ,                              CW_TOGG, KC_COPY, KC_PSTE, XXXXXXX, XXXXXXX,
                        KC_KB_VOLUME_DOWN, KC_F4  , KC_F5  , KC_F6  , KC_F11 ,                              TD_LEFT, TD_DOWN, TD_UP  , TD_RGHT, KC_QUOT,
                        KC_KB_MUTE       , KC_F1  , KC_F2  , KC_F3  , KC_F12 ,                              KC_MPRV, KC_MPLY, KC_MNXT, XXXXXXX, XXXXXXX,
                                                                      XXXXXXX, XXXXXXX,            XXXXXXX, XXXXXXX
                        ),
};

/*
 * RGB lighting
 */
#ifdef RGBLIGHT_ENABLE
#include "rgb_led.c"
#endif
#ifdef ENCODER_ENABLE
        #include "encoder.c"
#endif

layer_state_t default_layer_state_set_user(layer_state_t state) {
#ifdef RGBLIGHT_ENABLE
    rgblight_set_layer_state(_BASE, layer_state_cmp(state, _BASE));
#endif
    return state;
}

layer_state_t layer_state_set_user(layer_state_t state) {
#ifdef RGBLIGHT_ENABLE
    rgblight_set_layer_state(_NUMPAD, layer_state_cmp(state, _NUMPAD));
    rgblight_set_layer_state(_NAV, layer_state_cmp(state, _NAV));
    rgblight_set_layer_state(_SYMBOLS, layer_state_cmp(state, _SYMBOLS));
    rgblight_set_layer_state(_FUNCTION, layer_state_cmp(state, _FUNCTION));
    rgblight_set_layer_state(_UCIS, layer_state_cmp(state, _UCIS));
#endif
    return state;
}

/*
 * Custom keycode handling
 */
uint8_t mod_state;
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
        mod_state = get_mods();
        switch (keycode) {
                case CC_ARIN:
                // Å
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x00C5);
                                }else{
                                        register_unicode(0x00E5);
                                }
                                return false;
                        }
                        break;
                case CC_ADIA:
                // Ä
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x00C4);
                                }else{
                                        register_unicode(0x00E4);
                                }
                                return false;
                        }
                        break;
                case CC_ODIA:
                // Ö
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x00D6);
                                }else{
                                        register_unicode(0x00F6);
                                }
                                return false;
                        }
                        break;
                case CC_ALPH:
                // α
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x0391);
                                }else{
                                        register_unicode(0x03B1);
                                }
                                return false;
                        }
                        break;
                case CC_BETA:
                // β
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x0392);
                                }else{
                                        register_unicode(0x03B2);
                                }
                                return false;
                        }
                        break;
                case CC_GAMM:
                // γ
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x0393);
                                }else{
                                        register_unicode(0x03B3);
                                }
                                return false;
                        }
                        break;
                case CC_DELT:
                // δ
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x0394);
                                }else{
                                        register_unicode(0x03B4);
                                }
                                return false;
                        }
                        break;
                case CC_SIGM:
                // 
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x03A3);
                                }else{
                                        register_unicode(0x03C3);
                                }
                                return false;
                        }
                        break;
                case CC_RHO:
                // ρ
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x03A1);
                                }else{
                                        register_unicode(0x03C1);
                                }
                                return false;
                        }
                        break;
                case CC_PI:
                // π
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x03A0);
                                }else{
                                        register_unicode(0x03C0);
                                }
                                return false;
                        }
                        break;
                case CC_SNEK:
                // 🐍
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        register_unicode(0x1F40D);
                                }else{
                                        register_unicode(0x1F40D);
                                }
                                return false;
                        }
                        break;
                case KC_BSPC:
                // Left Shift + Backspace gives Delete
                        static bool delkey_registered;
                        if (record->event.pressed) {
                                if (mod_state & MOD_MASK_SHIFT) {
                                        del_mods(MOD_MASK_SHIFT);
                                        register_code(KC_DEL);
                                        delkey_registered = true;
                                        set_mods(mod_state);
                                        return false;
                                }
                        } else {
                                if (delkey_registered) {
                                        unregister_code(KC_DEL);
                                        delkey_registered = false;
                                        return false;
                                }
                        }
                case KC_ENT:
                case KC_SPC:
                case KC_ESC:
                // End UCIS input
                // BSPC, ENT, SPC, ESC can all be used to end UCIS input and thus should turn off the _UCIS layer
                        if (record->event.pressed) {
                                if (get_highest_layer(layer_state) == _UCIS){
                                        layer_off(_UCIS);
                                }
                                break;
                        }
                default:
                        break;
        }
        return true;
}


void post_process_record_user(uint16_t keycode, keyrecord_t *record){}

uint16_t keycode_config(uint16_t keycode) {
    return keycode;
}

uint8_t mod_config(uint8_t mod) {
    return mod;
}
